export const dummyInterviews: Interview[] = [
    {
    id:"1",
    userId:"user1",
    role:"Front-end Developer",
    type:"Technical",
    techstack:["React", "TypeScript", "Next.js", "Tailwind CSS"],
    level:"Junior",
    questions: ["What is React"],
    finalized: false,
    createdAt:"2025-03-15T10:00:00Z",
},
{
    id:"2",
    userId:"user2",
    role:"Back-end Developer",
    type:"Technical",
    techstack:["Node.js", "Express.js", "MongoDB"],
    level:"Junior",
    questions: ["What is Node.js"],
    finalized: false,
    createdAt:"2025-03-15T10:00:00Z",
},
{
    id:"3",
    userId:"user3",
    role:"Full-stack Developer",
    type:"Technical",
    techstack:["React", "Node.js", "Express.js", "MongoDB"],
    level:"Senior",
    questions: ["What is React", "What is Node.js"],
    finalized: false,
    createdAt:"2025-03-15T10:00:00Z",
},
]